version: "3"
services:
  zdb001:
    image: mariadb:10.3
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
    container_name: zdb001
  zsv001:
    image: zabbix/zabbix-server-mysql:centos-latest
    environment:
      - DB_SERVER_HOST=zdb001
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
      - ZBX_DEBUGLEVEL=3
    ports:
      - "10051:10051"
      - "10022:22"
    links:
      - zdb001
    container_name: zsv001
  zwb001:
    image: zabbix/zabbix-web-apache-mysql:centos-latest
    environment:
      - ZBX_SERVER_HOST=zsv001
      - DB_SERVER_HOST=zdb001
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
      - PHP_TZ=Asia/Tokyo
    ports:
      - 8080:80
    links:
      - zsv001
      - zdb001
    container_name: zwb001
  zag001:
    image: zabbix/zabbix-agent:centos-latest
    privileged: true
    environment:
      - ZBX_SERVER_HOST=zsv001
    expose:
      - "10050"
      - "22"
    links:
      - zsv001
    container_name: zag001
