version: "2"
services:
  zdb001:
    image: mariadb:10.4
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
    privileged: true
    container_name: zdb001
    hostname: zdb001
    networks:
      int_net:
        ipv4_address: 172.19.0.4

  zsv001:
    image: zabbix/zabbix-server-mysql:centos-latest
#    build:
#      context: .
#      dockerfile: Dockerfile_zsv001
    environment:
      - DB_SERVER_HOST=zdb001
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
      - ZBX_DEBUGLEVEL=3
    privileged: true
    ports:
      - "20051:10051"
      - "9004:22"
    expose:
      - "10051"      
    links:
      - zdb001
    container_name: zsv001
    hostname: zsv001
    networks:
      int_net:
        ipv4_address: 172.19.0.6

  zwb001:
    image: zabbix/zabbix-web-apache-mysql:centos-latest
#    build:
#      context: .
#      dockerfile: Dockerfile_zwb001
    environment:
      - ZBX_SERVER_HOST=zsv001
      - DB_SERVER_HOST=zdb001
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
      - PHP_TZ=Asia/Tokyo
    privileged: true
    ports:
      - "8080:80"
      - "9001:22"
    links:
      - zsv001
      - zdb001
    container_name: zwb001
    hostname: zwb001
    networks:
      int_net:
        ipv4_address: 172.19.0.3
      ext_net:
        ipv4_address: 172.20.0.3

  zag001:
    image: zabbix/zabbix-agent:centos-latest
#    build:
#      context: .
#      dockerfile: Dockerfile_zag001
    privileged: true
    environment:
      - ZBX_SERVER_HOST=zsv001
    ports: 
      - "9003:22"
    expose:
      - "10050"
    links:
      - zsv001
    container_name: zag001
    hostname: zag001
    networks:
      int_net:
        ipv4_address: 172.19.0.5

networks:
  int_net:
    external: true
  ext_net:
    external: true